### ISSUE TITLE
asdk-installer.ps1 - Get Logs option after first deployment failure (and/or -rerun)

### ISSUE THREAD

**Issue by charlesjoy** [Azure/AzureStack-Tools#289]
Currently it takes to -rerun attempts for the installer UX to show the Get Logs option. Showing this immediately (before a -rerun attempt) and after a -rerun attempt would be optimal, as we may need to gather logs at any time once deployment has kicked off (whether failures occur within deployment, or post deployment).

**Comment by marcvaneijk** [comment]
@charlesjoy sorry for the late reply. Would you prefer to have the button show as get-logs immediately after a failed deployment when starting the script, or still have the rerun option once, and then for the second time show the get-logs options (Since it is the same button, its either one or the other)

**Comment by marcvaneijk** [comment]
Inactive. Closing issue.
