### ISSUE TITLE
Is there a way to remove Guest Directory Tenant from my Azure Stack Deployment

### ISSUE THREAD

**Issue by slavizh** [Azure/AzureStack-Tools#402]
Hi there is no cmdlet Unregister-AzsGuestDirectoryTenant to remove  Guest Directory Tenant from Azure Stack Deployment. Please provide such option.

**Comment by yusukeMatsu** [comment]
FYI. I created "Unregister-AzsGuestDirectoryTenant" and send Pull Request(https://github.com/Azure/AzureStack-Tools/pull/394).

**Comment by slavizh** [comment]
Awesome. Thank you.

**Comment by keystroke** [comment]
Hello, we've been working on this feature internally and have prepared PR #403 for both parties to "unregister" a directory tenant from an Azure Stack deployment. You'll notice there are 2 new cmdlets added; one for the admin to revoke access from the directory, but also one to cleanup all the applications and permissions which were installed into that directory. PR #394 linked above by @yusukeMatsu shows how to do the first portion of this, which just involves deleting that resource through ARM. Note that you first have to "delete" any subscriptions which were created in that directory, otherwise ARM will block the deletion.
