### ISSUE TITLE
CloudID was not found issue during Unregistration

### ISSUE THREAD

**Issue by fengatgithub** [Azure/AzureStack-Tools#478]
AzureStack-Tools/Registration/RegisterWithAzure.psm1
$resourceCloudId = (($resourceObject.Properties.ToString()) | ConvertFrom-Json).cloudId
May not get cloudId during unregistration. will throw out error like in the following script: 
Registration resource with matching CloudId property f9f86733-17f1-4a33-afe1-5eb40bc6deb0 was not found. Please ensure a registration resource exists in the 
provided subscription & resource group.
At C:\AzureStack-Tools-master\Registration\RegisterWithAzure.psm1:1852 char:5

Change the command like below can fix it. 
$resourceCloudId = $resourceObject.Properties.cloudId.ToString()

**Comment by BradleyBartlett** [comment]
Hi @fengatgithub thanks for bringing this up. This is actually dependent on the version of AzureRm.Resources that is being used. The version used in AZURESTACK has a bug for how properties are returned on a resource so passing the properties to string and then to ConvertFrom-Json works around this. That being said, this function is not meant to run on the stamp as it is for the Azure side of the disconnected process.  Because of this I have updated the script similar to how you suggested. Thank you for your help. 

**example:** 
```
PS C:\Windows\system32> $resourceObject.Properties

HasValues    : False
Type         : String
Parent       : {}
Root         : {cloudId, objectId, billingModel}
Next         : 
Previous     : 
Path         : cloudId
First        : 
Last         : 
LineNumber   : 0
LinePosition : 0


PS C:\Windows\system32> (($resourceObject.Properties.ToString()) | ConvertFrom-Json).cloudid

0c34d1ef-a5db-4c93-a5af-7eb46fed02e2
```
